Update local port to 3003
gridsuite/gridadmin-app pull request #25
Opened 2024-03-28 14:17 UTC by flomillot

2024-03-28 15:09 UTC, Tristan-WorkGH requested changes

2024-03-28 15:09 UTC, Tristan-WorkGH commented on package.json
> +        "start": "PORT=3003 react-scripts start",
```suggestion
        "start": "PORT=3002 react-scripts start",
```

2024-03-28 15:09 UTC, Tristan-WorkGH commented on public/idpSettings.json
> +    "silent_redirect_uri": "http://localhost:3003/silent-renew-callback",
```suggestion
    "redirect_uri": "http://localhost:3002/sign-in-callback",
    "post_logout_redirect_uri": "http://localhost:3002/logout-callback",
    "silent_redirect_uri": "http://localhost:3002/silent-renew-callback",
```

2024-03-28 16:48 UTC, flomillot commented on package.json
> +        "start": "PORT=3003 react-scripts start",
Done

2024-03-28 16:48 UTC, flomillot commented on public/idpSettings.json
> +    "silent_redirect_uri": "http://localhost:3003/silent-renew-callback",
Done

2024-03-28 17:24 UTC, Tristan-WorkGH approved these changes

2024-03-29 08:29 UTC, EstherDarkish approved these changes

2024-04-02 10:31 UTC, merged